INSERT INTO FRUIT(ID, NAME, COLOR, ORIGIN_ID, PRICE) VALUES (1, 'Cherry', 'Red', 'Germany', 1.99);
INSERT INTO FRUIT(ID, NAME, COLOR, ORIGIN_ID, PRICE) VALUES (2, 'Apple', 'Red', 'Germany', 1.49);
INSERT INTO FRUIT(ID, NAME, COLOR, ORIGIN_ID, PRICE) VALUES (3, 'Banana', 'Yellow', 'Peru', 1.19);
INSERT INTO FRUIT(ID, NAME, COLOR, ORIGIN_ID, PRICE) VALUES (4, 'Avocado', 'Green', 'Peru', 1.49);
INSERT INTO FRUIT(ID, NAME, COLOR, ORIGIN_ID, PRICE) VALUES (5, 'Strawberry', 'Red', 'Netherlands', 2.39);
