INSERT INTO FRUIT(ID, NAME, COLOR, PRICE) VALUES (1, 'Cherry', 'Red', 1.99);
INSERT INTO FRUIT(ID, NAME, COLOR, PRICE) VALUES (2, 'Apple', 'Red', 1.49);
INSERT INTO FRUIT(ID, NAME, COLOR, PRICE) VALUES (3, 'Banana', 'Yellow', 1.19);
INSERT INTO FRUIT(ID, NAME, COLOR, PRICE) VALUES (4, 'Avocado', 'Green', 1.49);
INSERT INTO FRUIT(ID, NAME, COLOR, PRICE) VALUES (5, 'Strawberry', 'Red', 2.39);
